// src/app/eventDatabase.js

export const eventsData = [
    {
      id: 1,
      name: "Skill Enhancement Workshop",
      year: 2024,
      month: "August",
      location: "Mumbai, India",
      image: "/images/sdw.jpg",
      description: "A workshop focused on enhancing skills relevant to the market needs.",
    },
    {
      id: 2,
      name: "Shopkeeper Support Group",
      year: 2024,
      month: "September",
      location: "Delhi, India",
      image: "/images/ssg.jpg",
      description: "A support group for shopkeepers to share experiences and strategies.",
    },
    {
      id: 3,
      name: "Local Vendor Market Day",
      year: 2023,
      month: "July",
      location: "Bangalore, India",
      image: "/images/lvmd.jpg",
      description: "A market day event for local vendors to showcase their products.",
    },
    {
      id: 4,
      name: "Street Vendor Meet-Up",
      year: 2024,
      month: "March",
      location: "Hyderabad, India",
      image: "/images/swm.webp",
      description: "A meet-up event for street vendors to discuss common challenges.",
    },
    {
      id: 5,
      name: "Business Growth Seminar",
      year: 2023,
      month: "December",
      location: "Pune, India",
      image: "/images/bgs.jpg",
      description: "A seminar focused on strategies for small business growth.",
    },
    {
      id: 6,
      name: "Community Networking Meet",
      year: 2024,
      month: "January",
      location: "Gurgaon, India",
      image: "/images/CommunityMeet.jpg",
      description: "An event for networking within the local community.",
    },
    {
      id: 7,
      name: "Music Festival",
      year: 2023,
      month: "October",
      location: "Goa, India",
      image: "/images/MusicFestive.avif",
      description: "A festival featuring various music genres and local artists.",
    },
    {
      id: 8,
      name: "Trade Skill Training Program",
      year: 2024,
      month: "June",
      location: "Kolkata, India",
      image: "/images/trade-skill.jpg",
      description: "Training sessions for enhancing trade skills.",
    },
    {
      id: 9,
      name: "Food Carnival",
      year: 2023,
      month: "May",
      location: "Chennai, India",
      image: "/images/foodCarnival.webp",
      description: "A carnival celebrating diverse food cultures.",
    },
    {
      id: 10,
      name: "Neighborhood Bazaar",
      year: 2024,
      month: "February",
      location: "Jaipur, India",
      image: "/images/bazar.jpeg",
      description: "A bazaar showcasing local products and crafts.",
    },
  ];
  